## Algoritmo para resolver un sistema $Ax = b$ por el método de iteración de Jacobi

#### Implementacion matricial (vectorizada)

In [2]:
import numpy as np
from numpy import linalg as LA

In [1]:
def Jacobi(A,b,nmax,tol):
  n=len(b)
  # extract diagonal as a vector
  D=np.diag(A)
  # substract diagonal as a matrix (call "diag" again)
  LU = A-np.diag(D)
  x=np.zeros(n)
  k=0
  error=10
  while ( k < nmax and tol < error):
    k +=1
    xnew=(b-np.dot(LU,x))/D
    error=LA.norm(xnew-x)
    print("solucion x para la iteracion k= %2d con error %5.4f"%(k,error))
    print(" ",xnew)
    x=xnew
  if k==nmax:
    print("maximo numero de iteraciones fue alcanzado. ")
    print("probablemente no hay convegencia ")

In [3]:
A = np.array([[5.,-2.,3.],
              [-3.,8.,1.],
              [-3.,-1.,-6.]])

In [4]:
b = np.array([-1.,4.,0.])

In [5]:
nmax=1000
tol=0.0001

In [6]:
Jacobi(A,b,nmax,tol)

solucion x para la iteracion k=  1 con error 0.5385
  [-0.2  0.5 -0. ]
solucion x para la iteracion k=  2 con error 0.2142
  [0.         0.425      0.01666667]
solucion x para la iteracion k=  3 con error 0.1207
  [-0.04        0.49791667 -0.07083333]
solucion x para la iteracion k=  4 con error 0.0821
  [ 0.04166667  0.49385417 -0.06298611]
solucion x para la iteracion k=  5 con error 0.0503
  [ 0.03533333  0.52349826 -0.10314236]
solucion x para la iteracion k=  6 con error 0.0361
  [ 0.07128472  0.5261428  -0.10491638]
solucion x para la iteracion k=  7 con error 0.0231
  [ 0.07340694  0.53984632 -0.12333283]
solucion x para la iteracion k=  8 con error 0.0171
  [ 0.08993822  0.54294421 -0.12667786]
solucion x para la iteracion k=  9 con error 0.0115
  [ 0.0931844   0.54956157 -0.13545981]
solucion x para la iteracion k= 10 con error 0.0087
  [ 0.10110051  0.55187663 -0.13818579]
solucion x para la iteracion k= 11 con error 0.0060
  [ 0.10366213  0.55518592 -0.14252969]
solucion x p